import Head from "next/head";
import React from "react";
import Link from "next/link";
const Layout: React.FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark position-static">
        <Link href="/">
          <a className="navbar-brand user-select-none">Home</a>
        </Link>

        <button
          className="navbar-toggler "
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav mr-auto">
            <li className="nav-item active">
              <Link href="/games">
                <a className="nav-link user-select-none">All Games By Name</a>
              </Link>
            </li>
            <li className="nav-item active">
              <Link href="/platforms">
                <a className="nav-link user-select-none">
                  All Platforms By Name
                </a>
              </Link>
            </li>
          </ul>
        </div>
      </nav>
      <div id="main-page">{children}</div>
    </>
  );
};
export default Layout;
